export const champion = [
  {cost: 5, name: '갈리오'},
  {cost: 3, name: '갱플랭크'},
  {cost: 3, name: '나르'},
  {cost: 1, name: '녹턴'},
  {cost: 1, name: '다리우스'},
  {cost: 4, name: '드레이븐'},
  {cost: 4, name: '레나타 글라스크'},
  {cost: 3, name: '레오나'},
  {cost: 2, name: '렉사이'},
  {cost: 3, name: '루시안'},
  {cost: 2, name: '룰루'},
  {cost: 3, name: '말자하'},
  {cost: 3, name: '모르가나'},
  {cost: 3, name: '미스 포츈'},
  {cost: 4, name: '바이'},
  {cost: 5, name: '베이가'},
  {cost: 3, name: '벡스'},
  {cost: 4, name: '브라움'},
  {cost: 1, name: '브랜드'},
  {cost: 2, name: '블리츠크랭크'},
  {cost: 5, name: '빅토르'},
  {cost: 1, name: '뽀삐'},
  {cost: 3, name: '세나'},
  {cost: 4, name: '세라핀'},
  {cost: 2, name: '세주아니'},
  {cost: 2, name: '스웨인'},
  {cost: 4, name: '시비르'},
  {cost: 2, name: '신드라'},
  {cost: 1, name: '신지드'},
  {cost: 5, name: '실코'},
  {cost: 4, name: '아리'},
  {cost: 4, name: '알리스타'},
  {cost: 2, name: '애쉬'},
  {cost: 3, name: '에코'},
  {cost: 4, name: '오리아나'},
  {cost: 2, name: '워윅'},
  {cost: 4, name: '이렐리아'},
  {cost: 1, name: '이즈리얼'},
  {cost: 1, name: '일라오이'},
  {cost: 1, name: '자르반 4세'},
  {cost: 2, name: '자이라'},
  {cost: 3, name: '자크'},
  {cost: 5, name: '제리'},
  {cost: 5, name: '제이스'},
  {cost: 1, name: '직스'},
  {cost: 4, name: '진'},
  {cost: 2, name: '질리언'},
  {cost: 5, name: '징크스'},
  {cost: 3, name: '초가스'},
  {cost: 1, name: '카밀'},
  {cost: 1, name: '카사딘'},
  {cost: 5, name: '카이사'},
  {cost: 4, name: '카직스'},
  {cost: 1, name: '케이틀린'},
  {cost: 2, name: '코르키'},
  {cost: 4, name: '퀸'},
  {cost: 2, name: '탈론'},
  {cost: 5, name: '탐 켄치'},
  {cost: 3, name: '트린다미어'},
  {cost: 1, name: '트위치'},
];
