export const champion = [
  {cost: 1, name: '가렌'},
  {cost: 5, name: '갈리오'},
  {cost: 3, name: '갱플랭크'},
  {cost: 1, name: '그레이브즈'},
  {cost: 1, name: '다리우스'},
  {cost: 4, name: '럭스'},
  {cost: 3, name: '레오나'},
  {cost: 2, name: '룰루'},
  {cost: 3, name: '리산드라'},
  {cost: 3, name: '말자하'},
  {cost: 4, name: '문도 박사'},
  {cost: 3, name: '미스 포츈'},
  {cost: 3, name: '바이'},
  {cost: 3, name: '벡스'},
  {cost: 4, name: '브라움'},
  {cost: 2, name: '블리츠크랭크'},
  {cost: 5, name: '빅토르'},
  {cost: 1, name: '뽀삐'},
  {cost: 3, name: '사미라'},
  {cost: 4, name: '사이온'},
  {cost: 3, name: '샤코'},
  {cost: 4, name: '세라핀'},
  {cost: 2, name: '스웨인'},
  {cost: 1, name: '신지드'},
  {cost: 5, name: '아칼리'},
  {cost: 3, name: '에코'},
  {cost: 4, name: '오리아나'},
  {cost: 4, name: '요네'},
  {cost: 4, name: '우르곳'},
  {cost: 2, name: '워윅'},
  {cost: 5, name: '유미'},
  {cost: 1, name: '이즈리얼'},
  {cost: 1, name: '일라오이'},
  {cost: 2, name: '자이라'},
  {cost: 3, name: '자크'},
  {cost: 4, name: '잔나'},
  {cost: 5, name: '제이스'},
  {cost: 1, name: '직스'},
  {cost: 4, name: '진'},
  {cost: 2, name: '질리언'},
  {cost: 5, name: '징크스'},
  {cost: 3, name: '초가스'},
  {cost: 1, name: '카밀'},
  {cost: 1, name: '카사딘'},
  {cost: 5, name: '카이사'},
  {cost: 2, name: '카타리나'},
  {cost: 1, name: '케이틀린'},
  {cost: 2, name: '코그모'},
  {cost: 2, name: '퀸'},
  {cost: 3, name: '타릭'},
  {cost: 2, name: '탈론'},
  {cost: 5, name: '탐 켄치'},
  {cost: 2, name: '트런들'},
  {cost: 2, name: '트리스타나'},
  {cost: 1, name: '트위스티드 페이트'},
  {cost: 1, name: '트위치'},
  {cost: 4, name: '피오라'},
  {cost: 3, name: '하이머딩거'},
];
