export const mainData = [
  {
    cost: 1,
    img: require('../champion/Garen.png'),
    name: '가렌',
    synergy: ['아카데미', '봉쇄자'],
  },
  {
    cost: 5,
    img: require('../champion/Galio.png'),
    name: '갈리오',
    synergy: ['사교계', '거신', '경호대'],
  },
  {
    cost: 3,
    img: require('../champion/Gangplank.png'),
    name: '갱플랭크',
    synergy: ['용병', '쌍발총'],
  },
  {
    cost: 1,
    img: require('../champion/Graves.png'),
    name: '그레이브즈',
    synergy: ['아카데미', '쌍발총'],
  },
  {
    cost: 1,
    img: require('../champion/Darius.png'),
    name: '다리우스',
    synergy: ['범죄 조직', '경호대'],
  },
  {
    cost: 4,
    img: require('../champion/Lux.png'),
    name: '럭스',
    synergy: ['아카데미', '비전 마법사'],
  },
  {
    cost: 3,
    img: require('../champion/Leona.png'),
    name: '레오나',
    synergy: ['아카데미', '경호대'],
  },
  {
    cost: 2,
    img: require('../champion/Lulu.png'),
    name: '룰루',
    synergy: ['요들', '강화술사'],
  },
  {
    cost: 3,
    img: require('../champion/Lissandra.png'),
    name: '리산드라',
    synergy: ['화학공학', '학자'],
  },
  {
    cost: 3,
    img: require('../champion/Malzahar.png'),
    name: '말자하',
    synergy: ['돌연변이', '비전 마법사'],
  },
  {
    cost: 4,
    img: require('../champion/DrMundo.png'),
    name: '문도 박사',
    synergy: ['돌연변이', '화학공학', '난동꾼'],
  },
  {
    cost: 3,
    img: require('../champion/MissFortune.png'),
    name: '미스 포츈',
    synergy: ['용병', '저격수'],
  },
  {
    cost: 3,
    img: require('../champion/Vi.png'),
    name: '바이',
    synergy: ['자매', '집행자', '난동꾼'],
  },
  {
    cost: 3,
    img: require('../champion/Vex.png'),
    name: '벡스',
    synergy: ['요들', '비전 마법사'],
  },
  {
    cost: 4,
    img: require('../champion/Braum.png'),
    name: '브라움',
    synergy: ['범죄 조직', '경호대'],
  },
  {
    cost: 2,
    img: require('../champion/Blitzcrank.png'),
    name: '블리츠크랭크',
    synergy: ['고물상', '경호대', '봉쇄자'],
  },
  {
    cost: 5,
    img: require('../champion/Viktor.png'),
    name: '빅토르',
    synergy: ['화학공학', '비전 마법사'],
  },
  {
    cost: 1,
    img: require('../champion/Poppy.png'),
    name: '뽀삐',
    synergy: ['요들', '경호대'],
  },
  {
    cost: 3,
    img: require('../champion/Samira.png'),
    name: '사미라',
    synergy: ['제국', '도전자'],
  },
  {
    cost: 4,
    img: require('../champion/Sion.png'),
    name: '사이온',
    synergy: ['제국', '거신', '봉쇄자'],
  },
  {
    cost: 3,
    img: require('../champion/Shaco.png'),
    name: '샤코',
    synergy: ['범죄 조직', '암살자'],
  },
  {
    cost: 4,
    img: require('../champion/Seraphine.png'),
    name: '세라핀',
    synergy: ['사교계', '혁신가'],
  },
  {
    cost: 2,
    img: require('../champion/Swain.png'),
    name: '스웨인',
    synergy: ['제국', '비전 마법사'],
  },
  {
    cost: 1,
    img: require('../champion/Singed.png'),
    name: '신지드',
    synergy: ['화학공학', '혁신가'],
  },
  {
    cost: 5,
    img: require('../champion/Akali.png'),
    name: '아칼리',
    synergy: ['범죄 조직', '암살자'],
  },
  {
    cost: 3,
    img: require('../champion/Ekko.png'),
    name: '에코',
    synergy: ['고물상', '암살자'],
  },
  {
    cost: 4,
    img: require('../champion/Orianna.png'),
    name: '오리아나',
    synergy: ['시계태엽', '강화술사'],
  },
  {
    cost: 4,
    img: require('../champion/Yone.png'),
    name: '요네',
    synergy: ['아카데미', '도전자'],
  },
  {
    cost: 4,
    img: require('../champion/Urgot.png'),
    name: '우르곳',
    synergy: ['화학공학', '쌍발총'],
  },
  {
    cost: 2,
    img: require('../champion/Warwick.png'),
    name: '워윅',
    synergy: ['화학공학', '도전자'],
  },
  {
    cost: 5,
    img: require('../champion/Yuumi.png'),
    name: '유미',
    synergy: ['아카데미', '포근', '학자'],
  },
  {
    cost: 1,
    img: require('../champion/Ezreal.png'),
    name: '이즈리얼',
    synergy: ['고물상', '혁신가'],
  },
  {
    cost: 1,
    img: require('../champion/Illaoi.png'),
    name: '일라오이',
    synergy: ['용병', '난동꾼'],
  },
  {
    cost: 2,
    img: require('../champion/Zyra.png'),
    name: '자이라',
    synergy: ['범죄 조직', '학자'],
  },
  {
    cost: 3,
    img: require('../champion/Zac.png'),
    name: '자크',
    synergy: ['화학공학', '난동꾼'],
  },
  {
    cost: 4,
    img: require('../champion/Janna.png'),
    name: '잔나',
    synergy: ['고물상', '강화술사', '학자'],
  },
  {
    cost: 5,
    img: require('../champion/Jayce.png'),
    name: '제이스',
    synergy: ['집행자', '변형술사', '혁신가'],
  },
  {
    cost: 1,
    img: require('../champion/Ziggs.png'),
    name: '직스',
    synergy: ['고물상', '요들', '비전 마법사'],
  },
  {
    cost: 4,
    img: require('../champion/Jhin.png'),
    name: '진',
    synergy: ['시계태엽', '저격수'],
  },
  {
    cost: 2,
    img: require('../champion/Zilean.png'),
    name: '질리언',
    synergy: ['시계태엽', '혁신가'],
  },
  {
    cost: 5,
    img: require('../champion/Jinx.png'),
    name: '징크스',
    synergy: ['고물상', '자매', '쌍발총'],
  },
  {
    cost: 3,
    img: require('../champion/Chogath.png'),
    name: '초가스',
    synergy: ['돌연변이', '거신', '난동꾼'],
  },
  {
    cost: 1,
    img: require('../champion/Camille.png'),
    name: '카밀',
    synergy: ['시계태엽', '도전자'],
  },
  {
    cost: 1,
    img: require('../champion/Kassadin.png'),
    name: '카사딘',
    synergy: ['돌연변이', '봉쇄자'],
  },
  {
    cost: 5,
    img: require('../champion/Kaisa.png'),
    name: '카이사',
    synergy: ['돌연변이', '도전자'],
  },
  {
    cost: 2,
    img: require('../champion/Katarina.png'),
    name: '카타리나',
    synergy: ['아카데미', '암살자'],
  },
  {
    cost: 1,
    img: require('../champion/Caitlyn.png'),
    name: '케이틀린',
    synergy: ['집행자', '저격수'],
  },
  {
    cost: 2,
    img: require('../champion/KogMaw.png'),
    name: '코그모',
    synergy: ['돌연변이', '쌍발총', '저격수'],
  },
  {
    cost: 2,
    img: require('../champion/Quinn.png'),
    name: '퀸',
    synergy: ['용병', '도전자'],
  },
  {
    cost: 3,
    img: require('../champion/Taric.png'),
    name: '타릭',
    synergy: ['사교계', '강화술사'],
  },
  {
    cost: 2,
    img: require('../champion/Talon.png'),
    name: '탈론',
    synergy: ['제국', '암살자'],
  },
  {
    cost: 5,
    img: require('../champion/TahmKench.png'),
    name: '탐 켄치',
    synergy: ['대식가', '용병', '난동꾼'],
  },
  {
    cost: 2,
    img: require('../champion/Trundle.png'),
    name: '트런들',
    synergy: ['고물상', '난동꾼'],
  },
  {
    cost: 2,
    img: require('../champion/Tristana.png'),
    name: '트리스타나',
    synergy: ['요들', '저격수'],
  },
  {
    cost: 1,
    img: require('../champion/TwistedFate.png'),
    name: '트위스티드 페이트',
    synergy: ['범죄 조직', '비전 마법사'],
  },
  {
    cost: 1,
    img: require('../champion/Twitch.png'),
    name: '트위치',
    synergy: ['화학공학', '암살자'],
  },
  {
    cost: 4,
    img: require('../champion/Fiora.png'),
    name: '피오라',
    synergy: ['집행자', '도전자'],
  },
  {
    cost: 3,
    img: require('../champion/Heimerdinger.png'),
    name: '하이머딩거',
    synergy: ['요들', '학자', '혁신가'],
  },
];
