export const mainData = [
  {
    cost: 5,
    img: require('../champion/Galio.png'),
    name: '갈리오',
    synergy: ['사교계', '거신', '경호대'],
  },
  {
    cost: 3,
    img: require('../champion/Gangplank.png'),
    name: '갱플랭크',
    synergy: ['쌍발총', '용병'],
  },
  {
    cost: 3,
    img: require('../champion/Gnar.png'),
    name: '나르',
    synergy: ['타격대', '사교계', '요들'],
  },
  {
    cost: 1,
    img: require('../champion/Nocturne.png'),
    name: '녹턴',
    synergy: ['마법공학', '암살자'],
  },
  {
    cost: 1,
    img: require('../champion/Darius.png'),
    name: '다리우스',
    synergy: ['경호대', '범죄 조직'],
  },
  {
    cost: 4,
    img: require('../champion/Draven.png'),
    name: '드레이븐',
    synergy: ['연미복', '도전자'],
  },
  {
    cost: 4,
    img: require('../champion/Renata.png'),
    name: '레나타 글라스크',
    synergy: ['화학공학', '학자'],
  },
  {
    cost: 3,
    img: require('../champion/Leona.png'),
    name: '레오나',
    synergy: ['연미복', '경호대'],
  },
  {
    cost: 2,
    img: require('../champion/RekSai.png'),
    name: '렉사이',
    synergy: ['타격대', '돌연변이', '난동꾼'],
  },
  {
    cost: 3,
    img: require('../champion/Lucian.png'),
    name: '루시안',
    synergy: ['마법공학', '쌍발총'],
  },
  {
    cost: 2,
    img: require('../champion/Lulu.png'),
    name: '룰루',
    synergy: ['요들', '강화술사'],
  },
  {
    cost: 3,
    img: require('../champion/Malzahar.png'),
    name: '말자하',
    synergy: ['돌연변이', '비전 마법사'],
  },
  {
    cost: 3,
    img: require('../champion/Morgana.png'),
    name: '모르가나',
    synergy: ['강화술사', '범죄 조직'],
  },
  {
    cost: 3,
    img: require('../champion/MissFortune.png'),
    name: '미스 포츈',
    synergy: ['저격수', '용병'],
  },
  {
    cost: 4,
    img: require('../champion/Vi.png'),
    name: '바이',
    synergy: ['경쟁자', '집행자', '난동꾼'],
  },
  {
    cost: 3,
    img: require('../champion/Vex.png'),
    name: '벡스',
    synergy: ['요들', '비전 마법사'],
  },
  {
    cost: 4,
    img: require('../champion/Braum.png'),
    name: '브라움',
    synergy: ['경호대', '범죄 조직'],
  },
  {
    cost: 1,
    img: require('../champion/Brand.png'),
    name: '브랜드',
    synergy: ['연미복', '비전 마법사'],
  },
  {
    cost: 2,
    img: require('../champion/Blitzcrank.png'),
    name: '블리츠크랭크',
    synergy: ['경호대', '고물상'],
  },
  {
    cost: 5,
    img: require('../champion/Viktor.png'),
    name: '빅토르',
    synergy: ['화학공학', '비전 마법사'],
  },
  {
    cost: 1,
    img: require('../champion/Poppy.png'),
    name: '뽀삐',
    synergy: ['요들', '경호대'],
  },
  {
    cost: 3,
    img: require('../champion/Senna.png'),
    name: '세나',
    synergy: ['사교계', '강화술사'],
  },
  {
    cost: 4,
    img: require('../champion/Seraphine.png'),
    name: '세라핀',
    synergy: ['사교계', '혁신가'],
  },
  {
    cost: 2,
    img: require('../champion/Sejuani.png'),
    name: '세주아니',
    synergy: ['마법공학', '집행자', '난동꾼'],
  },
  {
    cost: 2,
    img: require('../champion/Swain.png'),
    name: '스웨인',
    synergy: ['마법공학', '비전 마법사'],
  },
  {
    cost: 4,
    img: require('../champion/Sivir.png'),
    name: '시비르',
    synergy: ['마법공학', '타격대'],
  },
  {
    cost: 2,
    img: require('../champion/Syndra.png'),
    name: '신드라',
    synergy: ['연미복', '학자'],
  },
  {
    cost: 1,
    img: require('../champion/Singed.png'),
    name: '신지드',
    synergy: ['화학공학', '혁신가'],
  },
  {
    cost: 5,
    img: require('../champion/Silco.png'),
    name: '실코',
    synergy: ['흑막', '학자'],
  },
  {
    cost: 4,
    img: require('../champion/Ahri.png'),
    name: '아리',
    synergy: ['비전 마법사', '범죄 조직'],
  },
  {
    cost: 4,
    img: require('../champion/Alistar.png'),
    name: '알리스타',
    synergy: ['마법공학', '거신'],
  },
  {
    cost: 2,
    img: require('../champion/Ashe.png'),
    name: '애쉬',
    synergy: ['저격수', '범죄 조직'],
  },
  {
    cost: 3,
    img: require('../champion/Ekko.png'),
    name: '에코',
    synergy: ['암살자', '혁신가', '고물상'],
  },
  {
    cost: 4,
    img: require('../champion/Orianna.png'),
    name: '오리아나',
    synergy: ['시계태엽', '강화술사'],
  },
  {
    cost: 2,
    img: require('../champion/Warwick.png'),
    name: '워윅',
    synergy: ['화학공학', '도전자'],
  },
  {
    cost: 4,
    img: require('../champion/Irelia.png'),
    name: '이렐리아',
    synergy: ['타격대', '고물상'],
  },
  {
    cost: 1,
    img: require('../champion/Ezreal.png'),
    name: '이즈리얼',
    synergy: ['혁신가', '고물상'],
  },
  {
    cost: 1,
    img: require('../champion/Illaoi.png'),
    name: '일라오이',
    synergy: ['난동꾼', '용병'],
  },
  {
    cost: 1,
    img: require('../champion/JarvanIV.png'),
    name: '자르반 4세',
    synergy: ['마법공학', '타격대'],
  },
  {
    cost: 2,
    img: require('../champion/Zyra.png'),
    name: '자이라',
    synergy: ['학자', '범죄 조직'],
  },
  {
    cost: 3,
    img: require('../champion/Zac.png'),
    name: '자크',
    synergy: ['화학공학', '난동꾼'],
  },
  {
    cost: 5,
    img: require('../champion/Zeri.png'),
    name: '제리',
    synergy: ['연미복', '저격수'],
  },
  {
    cost: 5,
    img: require('../champion/Jayce.png'),
    name: '제이스',
    synergy: ['집행자', '변형술사', '혁신가'],
  },
  {
    cost: 1,
    img: require('../champion/Ziggs.png'),
    name: '직스',
    synergy: ['요들', '비전 마법사', '고물상'],
  },
  {
    cost: 4,
    img: require('../champion/Jhin.png'),
    name: '진',
    synergy: ['시계태엽', '저격수'],
  },
  {
    cost: 2,
    img: require('../champion/Zilean.png'),
    name: '질리언',
    synergy: ['시계태엽', '혁신가'],
  },
  {
    cost: 5,
    img: require('../champion/Jinx.png'),
    name: '징크스',
    synergy: ['경쟁자', '쌍발총', '고물상'],
  },
  {
    cost: 3,
    img: require('../champion/Chogath.png'),
    name: '초가스',
    synergy: ['돌연변이', '거신', '난동꾼'],
  },
  {
    cost: 1,
    img: require('../champion/Camille.png'),
    name: '카밀',
    synergy: ['시계태엽', '도전자'],
  },
  {
    cost: 1,
    img: require('../champion/Kassadin.png'),
    name: '카사딘',
    synergy: ['돌연변이', '학자'],
  },
  {
    cost: 5,
    img: require('../champion/Kaisa.png'),
    name: '카이사',
    synergy: ['돌연변이', '도전자'],
  },
  {
    cost: 4,
    img: require('../champion/Khazix.png'),
    name: '카직스',
    synergy: ['돌연변이', '암살자'],
  },
  {
    cost: 1,
    img: require('../champion/Caitlyn.png'),
    name: '케이틀린',
    synergy: ['집행자', '저격수'],
  },
  {
    cost: 2,
    img: require('../champion/Corki.png'),
    name: '코르키',
    synergy: ['요들', '쌍발총'],
  },
  {
    cost: 2,
    img: require('../champion/Quinn.png'),
    name: '퀸',
    synergy: ['도전자', '용병'],
  },
  {
    cost: 2,
    img: require('../champion/Talon.png'),
    name: '탈론',
    synergy: ['연미복', '암살자'],
  },
  {
    cost: 5,
    img: require('../champion/TahmKench.png'),
    name: '탐 켄치',
    synergy: ['난동꾼', '대식가', '용병'],
  },
  {
    cost: 3,
    img: require('../champion/Tryndamere.png'),
    name: '트린다미어',
    synergy: ['화학공학', '도전자'],
  },
  {
    cost: 1,
    img: require('../champion/Twitch.png'),
    name: '트위치',
    synergy: ['화학공학', '암살자'],
  },
];
